2025-04-11 12:53:44,813 INFO    StreamThr :4234 [internal.py:wandb_internal():86] W&B internal server running at pid: 4234, started at: 2025-04-11 12:53:44.813121
2025-04-11 12:53:44,821 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: status
2025-04-11 12:53:44,910 INFO    WriterThread:4234 [datastore.py:open_for_write():85] open: /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/run-eutoc5dq.wandb
2025-04-11 12:53:44,912 DEBUG   SenderThread:4234 [sender.py:send():380] send: header
2025-04-11 12:53:44,912 DEBUG   SenderThread:4234 [sender.py:send():380] send: run
2025-04-11 12:53:45,755 INFO    SenderThread:4234 [dir_watcher.py:__init__():211] watching files in: /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/files
2025-04-11 12:53:45,755 INFO    SenderThread:4234 [sender.py:_start_run_threads():1122] run started: eutoc5dq with start time 1744376024.904776
2025-04-11 12:53:45,759 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: check_version
2025-04-11 12:53:45,759 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: check_version
2025-04-11 12:53:46,171 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: run_start
2025-04-11 12:53:46,192 DEBUG   HandlerThread:4234 [system_info.py:__init__():32] System info init
2025-04-11 12:53:46,192 DEBUG   HandlerThread:4234 [system_info.py:__init__():47] System info init done
2025-04-11 12:53:46,192 INFO    HandlerThread:4234 [system_monitor.py:start():194] Starting system monitor
2025-04-11 12:53:46,192 INFO    SystemMonitor:4234 [system_monitor.py:_start():158] Starting system asset monitoring threads
2025-04-11 12:53:46,193 INFO    HandlerThread:4234 [system_monitor.py:probe():214] Collecting system info
2025-04-11 12:53:46,194 INFO    SystemMonitor:4234 [interfaces.py:start():190] Started cpu monitoring
2025-04-11 12:53:46,195 INFO    SystemMonitor:4234 [interfaces.py:start():190] Started disk monitoring
2025-04-11 12:53:46,196 INFO    SystemMonitor:4234 [interfaces.py:start():190] Started gpu monitoring
2025-04-11 12:53:46,197 INFO    SystemMonitor:4234 [interfaces.py:start():190] Started memory monitoring
2025-04-11 12:53:46,198 INFO    SystemMonitor:4234 [interfaces.py:start():190] Started network monitoring
2025-04-11 12:53:46,249 DEBUG   HandlerThread:4234 [system_info.py:probe():196] Probing system
2025-04-11 12:53:46,251 DEBUG   HandlerThread:4234 [gitlib.py:_init_repo():53] git repository is invalid
2025-04-11 12:53:46,251 DEBUG   HandlerThread:4234 [system_info.py:probe():244] Probing system done
2025-04-11 12:53:46,252 DEBUG   HandlerThread:4234 [system_monitor.py:probe():223] {'os': 'Linux-4.15.0-213-generic-x86_64-with-glibc2.27', 'python': '3.10.15', 'heartbeatAt': '2025-04-11T12:53:46.249375', 'startedAt': '2025-04-11T12:53:44.805714', 'docker': None, 'cuda': None, 'args': ('--base_model', '../../../pretrained_mdls/ltuas_long_noqa_a6.bin', '--data_path', '/root/ltu-main/ltu-main/openasqa/data/meld_data.json', '--output_dir', '../exp/ltuas_ft_meld/', '--batch_size', '256', '--micro_batch_size', '1', '--num_epochs', '1', '--learning_rate', '2e-4', '--cutoff_len', '100', '--val_set_size', '0', '--lora_r', '8', '--lora_alpha', '16', '--lora_dropout', '0.05', '--lora_target_modules', '[q_proj,v_proj]', '--group_by_length', '--wandb_run_name', '../exp/ltuas_ft_meld/', '--save_steps', '30', '--trainable_params', 'all'), 'state': 'running', 'program': '/root/ltu-main/ltu-main/src/ltu_as/train_scripts/../finetune_low_resource.py', 'codePathLocal': None, 'host': 'ubuntu', 'username': 'root', 'executable': '/root/anaconda3/envs/venv_ltu/bin/python', 'cpu_count': 4, 'cpu_count_logical': 4, 'cpu_freq': {'current': 2294.598, 'min': 0.0, 'max': 0.0}, 'cpu_freq_per_core': [{'current': 2294.598, 'min': 0.0, 'max': 0.0}, {'current': 2294.598, 'min': 0.0, 'max': 0.0}, {'current': 2294.598, 'min': 0.0, 'max': 0.0}, {'current': 2294.598, 'min': 0.0, 'max': 0.0}], 'disk': {'/': {'total': 499.9882621765137, 'used': 333.20842361450195}}, 'gpu': 'NVIDIA A100-PCIE-40GB', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA A100-PCIE-40GB', 'memory_total': 42949672960}], 'memory': {'total': 19.60204315185547}}
2025-04-11 12:53:46,252 INFO    HandlerThread:4234 [system_monitor.py:probe():224] Finished collecting system info
2025-04-11 12:53:46,252 INFO    HandlerThread:4234 [system_monitor.py:probe():227] Publishing system info
2025-04-11 12:53:46,252 DEBUG   HandlerThread:4234 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2025-04-11 12:53:46,253 DEBUG   HandlerThread:4234 [system_info.py:_save_pip():68] Saving pip packages done
2025-04-11 12:53:46,253 DEBUG   HandlerThread:4234 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2025-04-11 12:53:46,756 INFO    Thread-12 :4234 [dir_watcher.py:_on_file_created():271] file/dir created: /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/files/requirements.txt
2025-04-11 12:53:46,757 INFO    Thread-12 :4234 [dir_watcher.py:_on_file_created():271] file/dir created: /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/files/conda-environment.yaml
2025-04-11 12:54:07,764 INFO    Thread-12 :4234 [dir_watcher.py:_on_file_modified():288] file/dir modified: /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/files/conda-environment.yaml
2025-04-11 12:54:07,873 DEBUG   HandlerThread:4234 [system_info.py:_save_conda():87] Saving conda packages done
2025-04-11 12:54:07,874 INFO    HandlerThread:4234 [system_monitor.py:probe():229] Finished publishing system info
2025-04-11 12:54:07,901 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: status_report
2025-04-11 12:54:07,901 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: keepalive
2025-04-11 12:54:07,902 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: status_report
2025-04-11 12:54:07,902 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: keepalive
2025-04-11 12:54:07,902 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: status_report
2025-04-11 12:54:07,902 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: keepalive
2025-04-11 12:54:07,902 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: status_report
2025-04-11 12:54:07,902 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: keepalive
2025-04-11 12:54:07,907 DEBUG   SenderThread:4234 [sender.py:send():380] send: files
2025-04-11 12:54:07,907 INFO    SenderThread:4234 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2025-04-11 12:54:07,910 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: stop_status
2025-04-11 12:54:07,910 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: stop_status
2025-04-11 12:54:07,915 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: internal_messages
2025-04-11 12:54:08,278 DEBUG   SenderThread:4234 [sender.py:send():380] send: telemetry
2025-04-11 12:54:08,281 DEBUG   SenderThread:4234 [sender.py:send():380] send: config
2025-04-11 12:54:08,282 DEBUG   SenderThread:4234 [sender.py:send():380] send: metric
2025-04-11 12:54:08,282 DEBUG   SenderThread:4234 [sender.py:send():380] send: telemetry
2025-04-11 12:54:08,283 DEBUG   SenderThread:4234 [sender.py:send():380] send: metric
2025-04-11 12:54:08,283 WARNING SenderThread:4234 [sender.py:send_metric():1329] Seen metric with glob (shouldn't happen)
2025-04-11 12:54:08,592 ERROR   wandb-upload_0:4234 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/2931823730-harbin-institute-of-technology/ltu-as/eutoc5dq/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250411%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250411T125408Z&X-Goog-Expires=86399&X-Goog-Signature=ad500f6e170e92326285082c14b28649e4a63f8d14b2e28396b83f04c180d0453b6a4b528a74a024d26a2216cc270aef455c145f4b1bc9d95fa6914cfb14dc3efec6a40dfa4ca518a698916a0f94176b7eb34a83c19157ee6866e596c217f5cc1a6237dc0b52202383e0954d65ba696383a8f73f5705174c0d9eff572d2312ebb0cd724c30afdb06e27edf39bfc1a643e018a392a8caa5abc44020e39e132b2434e215b470839f3df148179f63f499c5097c0cf232d6c3e47576bcb9ea84d794a3c1b4679d80bed497ccde47a518610538ce7e88ce4b06602e4d7d8111ee14948fafc21a7d35a0d0247a2d3e6d7d9554d2b428d7120a8719d6ae582e280c3e37&X-Goog-SignedHeaders=host&X-User=2931823730: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/2931823730-harbin-institute-of-technology/ltu-as/eutoc5dq/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250411%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250411T125408Z&X-Goog-Expires=86399&X-Goog-Signature=ad500f6e170e92326285082c14b28649e4a63f8d14b2e28396b83f04c180d0453b6a4b528a74a024d26a2216cc270aef455c145f4b1bc9d95fa6914cfb14dc3efec6a40dfa4ca518a698916a0f94176b7eb34a83c19157ee6866e596c217f5cc1a6237dc0b52202383e0954d65ba696383a8f73f5705174c0d9eff572d2312ebb0cd724c30afdb06e27edf39bfc1a643e018a392a8caa5abc44020e39e132b2434e215b470839f3df148179f63f499c5097c0cf232d6c3e47576bcb9ea84d794a3c1b4679d80bed497ccde47a518610538ce7e88ce4b06602e4d7d8111ee14948fafc21a7d35a0d0247a2d3e6d7d9554d2b428d7120a8719d6ae582e280c3e37&X-Goog-SignedHeaders=host&X-User=2931823730 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8ef0159d20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2025-04-11 12:54:08,593 ERROR   wandb-upload_0:4234 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2259'}
2025-04-11 12:54:08,593 ERROR   wandb-upload_0:4234 [internal_api.py:upload_file():2560] upload_file response body: 
2025-04-11 12:54:08,765 INFO    Thread-12 :4234 [dir_watcher.py:_on_file_created():271] file/dir created: /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/files/output.log
2025-04-11 12:54:08,766 INFO    Thread-12 :4234 [dir_watcher.py:_on_file_created():271] file/dir created: /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/files/wandb-metadata.json
2025-04-11 12:54:09,802 ERROR   wandb-upload_0:4234 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/2931823730-harbin-institute-of-technology/ltu-as/eutoc5dq/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250411%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250411T125408Z&X-Goog-Expires=86399&X-Goog-Signature=ad500f6e170e92326285082c14b28649e4a63f8d14b2e28396b83f04c180d0453b6a4b528a74a024d26a2216cc270aef455c145f4b1bc9d95fa6914cfb14dc3efec6a40dfa4ca518a698916a0f94176b7eb34a83c19157ee6866e596c217f5cc1a6237dc0b52202383e0954d65ba696383a8f73f5705174c0d9eff572d2312ebb0cd724c30afdb06e27edf39bfc1a643e018a392a8caa5abc44020e39e132b2434e215b470839f3df148179f63f499c5097c0cf232d6c3e47576bcb9ea84d794a3c1b4679d80bed497ccde47a518610538ce7e88ce4b06602e4d7d8111ee14948fafc21a7d35a0d0247a2d3e6d7d9554d2b428d7120a8719d6ae582e280c3e37&X-Goog-SignedHeaders=host&X-User=2931823730: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/2931823730-harbin-institute-of-technology/ltu-as/eutoc5dq/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250411%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250411T125408Z&X-Goog-Expires=86399&X-Goog-Signature=ad500f6e170e92326285082c14b28649e4a63f8d14b2e28396b83f04c180d0453b6a4b528a74a024d26a2216cc270aef455c145f4b1bc9d95fa6914cfb14dc3efec6a40dfa4ca518a698916a0f94176b7eb34a83c19157ee6866e596c217f5cc1a6237dc0b52202383e0954d65ba696383a8f73f5705174c0d9eff572d2312ebb0cd724c30afdb06e27edf39bfc1a643e018a392a8caa5abc44020e39e132b2434e215b470839f3df148179f63f499c5097c0cf232d6c3e47576bcb9ea84d794a3c1b4679d80bed497ccde47a518610538ce7e88ce4b06602e4d7d8111ee14948fafc21a7d35a0d0247a2d3e6d7d9554d2b428d7120a8719d6ae582e280c3e37&X-Goog-SignedHeaders=host&X-User=2931823730 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8ef015a080>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2025-04-11 12:54:09,802 ERROR   wandb-upload_0:4234 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2259'}
2025-04-11 12:54:09,802 ERROR   wandb-upload_0:4234 [internal_api.py:upload_file():2560] upload_file response body: 
2025-04-11 12:54:10,289 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: status_report
2025-04-11 12:54:10,765 INFO    Thread-12 :4234 [dir_watcher.py:_on_file_modified():288] file/dir modified: /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/files/output.log
2025-04-11 12:54:11,835 ERROR   wandb-upload_0:4234 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/2931823730-harbin-institute-of-technology/ltu-as/eutoc5dq/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250411%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250411T125408Z&X-Goog-Expires=86399&X-Goog-Signature=ad500f6e170e92326285082c14b28649e4a63f8d14b2e28396b83f04c180d0453b6a4b528a74a024d26a2216cc270aef455c145f4b1bc9d95fa6914cfb14dc3efec6a40dfa4ca518a698916a0f94176b7eb34a83c19157ee6866e596c217f5cc1a6237dc0b52202383e0954d65ba696383a8f73f5705174c0d9eff572d2312ebb0cd724c30afdb06e27edf39bfc1a643e018a392a8caa5abc44020e39e132b2434e215b470839f3df148179f63f499c5097c0cf232d6c3e47576bcb9ea84d794a3c1b4679d80bed497ccde47a518610538ce7e88ce4b06602e4d7d8111ee14948fafc21a7d35a0d0247a2d3e6d7d9554d2b428d7120a8719d6ae582e280c3e37&X-Goog-SignedHeaders=host&X-User=2931823730: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/2931823730-harbin-institute-of-technology/ltu-as/eutoc5dq/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250411%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250411T125408Z&X-Goog-Expires=86399&X-Goog-Signature=ad500f6e170e92326285082c14b28649e4a63f8d14b2e28396b83f04c180d0453b6a4b528a74a024d26a2216cc270aef455c145f4b1bc9d95fa6914cfb14dc3efec6a40dfa4ca518a698916a0f94176b7eb34a83c19157ee6866e596c217f5cc1a6237dc0b52202383e0954d65ba696383a8f73f5705174c0d9eff572d2312ebb0cd724c30afdb06e27edf39bfc1a643e018a392a8caa5abc44020e39e132b2434e215b470839f3df148179f63f499c5097c0cf232d6c3e47576bcb9ea84d794a3c1b4679d80bed497ccde47a518610538ce7e88ce4b06602e4d7d8111ee14948fafc21a7d35a0d0247a2d3e6d7d9554d2b428d7120a8719d6ae582e280c3e37&X-Goog-SignedHeaders=host&X-User=2931823730 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8ef015a290>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2025-04-11 12:54:11,835 ERROR   wandb-upload_0:4234 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2259'}
2025-04-11 12:54:11,835 ERROR   wandb-upload_0:4234 [internal_api.py:upload_file():2560] upload_file response body: 
2025-04-11 12:54:11,835 INFO    wandb-upload_0:4234 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8ef015a290>: Failed to establish a new connection: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/2931823730-harbin-institute-of-technology/ltu-as/eutoc5dq/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250411%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250411T125408Z&X-Goog-Expires=86399&X-Goog-Signature=ad500f6e170e92326285082c14b28649e4a63f8d14b2e28396b83f04c180d0453b6a4b528a74a024d26a2216cc270aef455c145f4b1bc9d95fa6914cfb14dc3efec6a40dfa4ca518a698916a0f94176b7eb34a83c19157ee6866e596c217f5cc1a6237dc0b52202383e0954d65ba696383a8f73f5705174c0d9eff572d2312ebb0cd724c30afdb06e27edf39bfc1a643e018a392a8caa5abc44020e39e132b2434e215b470839f3df148179f63f499c5097c0cf232d6c3e47576bcb9ea84d794a3c1b4679d80bed497ccde47a518610538ce7e88ce4b06602e4d7d8111ee14948fafc21a7d35a0d0247a2d3e6d7d9554d2b428d7120a8719d6ae582e280c3e37&X-Goog-SignedHeaders=host&X-User=2931823730 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8ef015a290>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/2931823730-harbin-institute-of-technology/ltu-as/eutoc5dq/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250411%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250411T125408Z&X-Goog-Expires=86399&X-Goog-Signature=ad500f6e170e92326285082c14b28649e4a63f8d14b2e28396b83f04c180d0453b6a4b528a74a024d26a2216cc270aef455c145f4b1bc9d95fa6914cfb14dc3efec6a40dfa4ca518a698916a0f94176b7eb34a83c19157ee6866e596c217f5cc1a6237dc0b52202383e0954d65ba696383a8f73f5705174c0d9eff572d2312ebb0cd724c30afdb06e27edf39bfc1a643e018a392a8caa5abc44020e39e132b2434e215b470839f3df148179f63f499c5097c0cf232d6c3e47576bcb9ea84d794a3c1b4679d80bed497ccde47a518610538ce7e88ce4b06602e4d7d8111ee14948fafc21a7d35a0d0247a2d3e6d7d9554d2b428d7120a8719d6ae582e280c3e37&X-Goog-SignedHeaders=host&X-User=2931823730 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8ef015a290>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2580, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2025-04-11 12:54:15,295 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: status_report
2025-04-11 12:54:15,768 INFO    Thread-12 :4234 [dir_watcher.py:_on_file_modified():288] file/dir modified: /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/files/config.yaml
2025-04-11 12:54:17,030 ERROR   wandb-upload_0:4234 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/2931823730-harbin-institute-of-technology/ltu-as/eutoc5dq/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250411%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250411T125408Z&X-Goog-Expires=86399&X-Goog-Signature=ad500f6e170e92326285082c14b28649e4a63f8d14b2e28396b83f04c180d0453b6a4b528a74a024d26a2216cc270aef455c145f4b1bc9d95fa6914cfb14dc3efec6a40dfa4ca518a698916a0f94176b7eb34a83c19157ee6866e596c217f5cc1a6237dc0b52202383e0954d65ba696383a8f73f5705174c0d9eff572d2312ebb0cd724c30afdb06e27edf39bfc1a643e018a392a8caa5abc44020e39e132b2434e215b470839f3df148179f63f499c5097c0cf232d6c3e47576bcb9ea84d794a3c1b4679d80bed497ccde47a518610538ce7e88ce4b06602e4d7d8111ee14948fafc21a7d35a0d0247a2d3e6d7d9554d2b428d7120a8719d6ae582e280c3e37&X-Goog-SignedHeaders=host&X-User=2931823730: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/2931823730-harbin-institute-of-technology/ltu-as/eutoc5dq/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250411%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250411T125408Z&X-Goog-Expires=86399&X-Goog-Signature=ad500f6e170e92326285082c14b28649e4a63f8d14b2e28396b83f04c180d0453b6a4b528a74a024d26a2216cc270aef455c145f4b1bc9d95fa6914cfb14dc3efec6a40dfa4ca518a698916a0f94176b7eb34a83c19157ee6866e596c217f5cc1a6237dc0b52202383e0954d65ba696383a8f73f5705174c0d9eff572d2312ebb0cd724c30afdb06e27edf39bfc1a643e018a392a8caa5abc44020e39e132b2434e215b470839f3df148179f63f499c5097c0cf232d6c3e47576bcb9ea84d794a3c1b4679d80bed497ccde47a518610538ce7e88ce4b06602e4d7d8111ee14948fafc21a7d35a0d0247a2d3e6d7d9554d2b428d7120a8719d6ae582e280c3e37&X-Goog-SignedHeaders=host&X-User=2931823730 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8ef015a2c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2025-04-11 12:54:17,030 ERROR   wandb-upload_0:4234 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2259'}
2025-04-11 12:54:17,030 ERROR   wandb-upload_0:4234 [internal_api.py:upload_file():2560] upload_file response body: 
2025-04-11 12:54:20,708 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: status_report
2025-04-11 12:54:22,909 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: internal_messages
2025-04-11 12:54:22,910 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: stop_status
2025-04-11 12:54:22,911 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: stop_status
2025-04-11 12:54:25,183 ERROR   wandb-upload_0:4234 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/2931823730-harbin-institute-of-technology/ltu-as/eutoc5dq/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250411%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250411T125408Z&X-Goog-Expires=86399&X-Goog-Signature=ad500f6e170e92326285082c14b28649e4a63f8d14b2e28396b83f04c180d0453b6a4b528a74a024d26a2216cc270aef455c145f4b1bc9d95fa6914cfb14dc3efec6a40dfa4ca518a698916a0f94176b7eb34a83c19157ee6866e596c217f5cc1a6237dc0b52202383e0954d65ba696383a8f73f5705174c0d9eff572d2312ebb0cd724c30afdb06e27edf39bfc1a643e018a392a8caa5abc44020e39e132b2434e215b470839f3df148179f63f499c5097c0cf232d6c3e47576bcb9ea84d794a3c1b4679d80bed497ccde47a518610538ce7e88ce4b06602e4d7d8111ee14948fafc21a7d35a0d0247a2d3e6d7d9554d2b428d7120a8719d6ae582e280c3e37&X-Goog-SignedHeaders=host&X-User=2931823730: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/2931823730-harbin-institute-of-technology/ltu-as/eutoc5dq/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250411%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250411T125408Z&X-Goog-Expires=86399&X-Goog-Signature=ad500f6e170e92326285082c14b28649e4a63f8d14b2e28396b83f04c180d0453b6a4b528a74a024d26a2216cc270aef455c145f4b1bc9d95fa6914cfb14dc3efec6a40dfa4ca518a698916a0f94176b7eb34a83c19157ee6866e596c217f5cc1a6237dc0b52202383e0954d65ba696383a8f73f5705174c0d9eff572d2312ebb0cd724c30afdb06e27edf39bfc1a643e018a392a8caa5abc44020e39e132b2434e215b470839f3df148179f63f499c5097c0cf232d6c3e47576bcb9ea84d794a3c1b4679d80bed497ccde47a518610538ce7e88ce4b06602e4d7d8111ee14948fafc21a7d35a0d0247a2d3e6d7d9554d2b428d7120a8719d6ae582e280c3e37&X-Goog-SignedHeaders=host&X-User=2931823730 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8ef015b760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2025-04-11 12:54:25,183 ERROR   wandb-upload_0:4234 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2259'}
2025-04-11 12:54:25,183 ERROR   wandb-upload_0:4234 [internal_api.py:upload_file():2560] upload_file response body: 
2025-04-11 12:54:26,257 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: status_report
2025-04-11 12:54:31,258 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: status_report
2025-04-11 12:54:31,802 DEBUG   SenderThread:4234 [sender.py:send():380] send: exit
2025-04-11 12:54:31,802 INFO    SenderThread:4234 [sender.py:send_exit():585] handling exit code: 1
2025-04-11 12:54:31,803 INFO    SenderThread:4234 [sender.py:send_exit():587] handling runtime: 45
2025-04-11 12:54:31,804 INFO    SenderThread:4234 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2025-04-11 12:54:31,805 INFO    SenderThread:4234 [sender.py:send_exit():593] send defer
2025-04-11 12:54:31,805 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: defer
2025-04-11 12:54:31,806 INFO    HandlerThread:4234 [handler.py:handle_request_defer():172] handle defer: 0
2025-04-11 12:54:31,806 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: defer
2025-04-11 12:54:31,806 INFO    SenderThread:4234 [sender.py:send_request_defer():609] handle sender defer: 0
2025-04-11 12:54:31,806 INFO    SenderThread:4234 [sender.py:transition_state():613] send defer: 1
2025-04-11 12:54:31,806 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: defer
2025-04-11 12:54:31,806 INFO    HandlerThread:4234 [handler.py:handle_request_defer():172] handle defer: 1
2025-04-11 12:54:31,807 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: defer
2025-04-11 12:54:31,807 INFO    SenderThread:4234 [sender.py:send_request_defer():609] handle sender defer: 1
2025-04-11 12:54:31,807 INFO    SenderThread:4234 [sender.py:transition_state():613] send defer: 2
2025-04-11 12:54:31,807 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: defer
2025-04-11 12:54:31,807 INFO    HandlerThread:4234 [handler.py:handle_request_defer():172] handle defer: 2
2025-04-11 12:54:31,807 INFO    HandlerThread:4234 [system_monitor.py:finish():203] Stopping system monitor
2025-04-11 12:54:31,807 DEBUG   SystemMonitor:4234 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2025-04-11 12:54:31,807 DEBUG   SystemMonitor:4234 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2025-04-11 12:54:31,807 DEBUG   SystemMonitor:4234 [system_monitor.py:_start():183] Publishing last batch of metrics
2025-04-11 12:54:31,808 INFO    HandlerThread:4234 [interfaces.py:finish():202] Joined cpu monitor
2025-04-11 12:54:31,808 INFO    HandlerThread:4234 [interfaces.py:finish():202] Joined disk monitor
2025-04-11 12:54:31,854 INFO    HandlerThread:4234 [interfaces.py:finish():202] Joined gpu monitor
2025-04-11 12:54:31,854 INFO    HandlerThread:4234 [interfaces.py:finish():202] Joined memory monitor
2025-04-11 12:54:31,854 INFO    HandlerThread:4234 [interfaces.py:finish():202] Joined network monitor
2025-04-11 12:54:31,855 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: defer
2025-04-11 12:54:31,855 INFO    SenderThread:4234 [sender.py:send_request_defer():609] handle sender defer: 2
2025-04-11 12:54:31,856 INFO    SenderThread:4234 [sender.py:transition_state():613] send defer: 3
2025-04-11 12:54:31,856 DEBUG   SenderThread:4234 [sender.py:send():380] send: stats
2025-04-11 12:54:31,856 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: defer
2025-04-11 12:54:31,856 INFO    HandlerThread:4234 [handler.py:handle_request_defer():172] handle defer: 3
2025-04-11 12:54:31,857 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: defer
2025-04-11 12:54:31,857 INFO    SenderThread:4234 [sender.py:send_request_defer():609] handle sender defer: 3
2025-04-11 12:54:31,857 INFO    SenderThread:4234 [sender.py:transition_state():613] send defer: 4
2025-04-11 12:54:31,857 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: defer
2025-04-11 12:54:31,857 INFO    HandlerThread:4234 [handler.py:handle_request_defer():172] handle defer: 4
2025-04-11 12:54:31,858 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: defer
2025-04-11 12:54:31,858 INFO    SenderThread:4234 [sender.py:send_request_defer():609] handle sender defer: 4
2025-04-11 12:54:31,858 INFO    SenderThread:4234 [sender.py:transition_state():613] send defer: 5
2025-04-11 12:54:31,858 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: defer
2025-04-11 12:54:31,858 INFO    HandlerThread:4234 [handler.py:handle_request_defer():172] handle defer: 5
2025-04-11 12:54:31,859 DEBUG   SenderThread:4234 [sender.py:send():380] send: summary
2025-04-11 12:54:31,891 INFO    SenderThread:4234 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2025-04-11 12:54:31,891 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: defer
2025-04-11 12:54:31,891 INFO    SenderThread:4234 [sender.py:send_request_defer():609] handle sender defer: 5
2025-04-11 12:54:31,891 INFO    SenderThread:4234 [sender.py:transition_state():613] send defer: 6
2025-04-11 12:54:31,892 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: defer
2025-04-11 12:54:31,892 INFO    HandlerThread:4234 [handler.py:handle_request_defer():172] handle defer: 6
2025-04-11 12:54:31,892 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: defer
2025-04-11 12:54:31,892 INFO    SenderThread:4234 [sender.py:send_request_defer():609] handle sender defer: 6
2025-04-11 12:54:31,892 INFO    SenderThread:4234 [sender.py:transition_state():613] send defer: 7
2025-04-11 12:54:31,893 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: status_report
2025-04-11 12:54:31,893 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: defer
2025-04-11 12:54:31,893 INFO    HandlerThread:4234 [handler.py:handle_request_defer():172] handle defer: 7
2025-04-11 12:54:31,894 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: defer
2025-04-11 12:54:31,894 INFO    SenderThread:4234 [sender.py:send_request_defer():609] handle sender defer: 7
2025-04-11 12:54:32,352 INFO    SenderThread:4234 [sender.py:transition_state():613] send defer: 8
2025-04-11 12:54:32,352 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: defer
2025-04-11 12:54:32,353 INFO    HandlerThread:4234 [handler.py:handle_request_defer():172] handle defer: 8
2025-04-11 12:54:32,353 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: defer
2025-04-11 12:54:32,353 INFO    SenderThread:4234 [sender.py:send_request_defer():609] handle sender defer: 8
2025-04-11 12:54:32,353 INFO    SenderThread:4234 [job_builder.py:build():281] Attempting to build job artifact
2025-04-11 12:54:32,354 INFO    SenderThread:4234 [job_builder.py:_get_source_type():404] no source found
2025-04-11 12:54:32,354 INFO    SenderThread:4234 [sender.py:transition_state():613] send defer: 9
2025-04-11 12:54:32,354 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: defer
2025-04-11 12:54:32,354 INFO    HandlerThread:4234 [handler.py:handle_request_defer():172] handle defer: 9
2025-04-11 12:54:32,355 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: defer
2025-04-11 12:54:32,355 INFO    SenderThread:4234 [sender.py:send_request_defer():609] handle sender defer: 9
2025-04-11 12:54:32,355 INFO    SenderThread:4234 [dir_watcher.py:finish():358] shutting down directory watcher
2025-04-11 12:54:32,772 INFO    SenderThread:4234 [dir_watcher.py:_on_file_modified():288] file/dir modified: /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/files/output.log
2025-04-11 12:54:32,773 INFO    SenderThread:4234 [dir_watcher.py:_on_file_created():271] file/dir created: /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/files/wandb-summary.json
2025-04-11 12:54:32,773 INFO    SenderThread:4234 [dir_watcher.py:finish():388] scan: /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/files
2025-04-11 12:54:32,774 INFO    SenderThread:4234 [dir_watcher.py:finish():402] scan save: /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/files/config.yaml config.yaml
2025-04-11 12:54:32,774 INFO    SenderThread:4234 [dir_watcher.py:finish():402] scan save: /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/files/requirements.txt requirements.txt
2025-04-11 12:54:32,779 INFO    SenderThread:4234 [dir_watcher.py:finish():402] scan save: /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/files/conda-environment.yaml conda-environment.yaml
2025-04-11 12:54:32,779 INFO    SenderThread:4234 [dir_watcher.py:finish():402] scan save: /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/files/wandb-metadata.json wandb-metadata.json
2025-04-11 12:54:32,782 INFO    SenderThread:4234 [dir_watcher.py:finish():402] scan save: /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/files/output.log output.log
2025-04-11 12:54:32,784 INFO    SenderThread:4234 [dir_watcher.py:finish():402] scan save: /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/files/wandb-summary.json wandb-summary.json
2025-04-11 12:54:32,787 INFO    SenderThread:4234 [sender.py:transition_state():613] send defer: 10
2025-04-11 12:54:32,787 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: defer
2025-04-11 12:54:32,787 INFO    HandlerThread:4234 [handler.py:handle_request_defer():172] handle defer: 10
2025-04-11 12:54:32,789 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: defer
2025-04-11 12:54:32,789 INFO    SenderThread:4234 [sender.py:send_request_defer():609] handle sender defer: 10
2025-04-11 12:54:32,790 INFO    SenderThread:4234 [file_pusher.py:finish():175] shutting down file pusher
2025-04-11 12:54:32,802 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: poll_exit
2025-04-11 12:54:32,803 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: poll_exit
2025-04-11 12:54:33,804 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: poll_exit
2025-04-11 12:54:33,804 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: poll_exit
2025-04-11 12:54:33,989 INFO    wandb-upload_2:4234 [upload_job.py:push():131] Uploaded file /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/files/requirements.txt
2025-04-11 12:54:34,002 INFO    wandb-upload_1:4234 [upload_job.py:push():131] Uploaded file /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/files/config.yaml
2025-04-11 12:54:34,010 INFO    wandb-upload_3:4234 [upload_job.py:push():131] Uploaded file /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/files/conda-environment.yaml
2025-04-11 12:54:34,044 INFO    wandb-upload_4:4234 [upload_job.py:push():131] Uploaded file /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/files/output.log
2025-04-11 12:54:34,057 INFO    wandb-upload_5:4234 [upload_job.py:push():131] Uploaded file /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/files/wandb-summary.json
2025-04-11 12:54:34,806 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: poll_exit
2025-04-11 12:54:34,807 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: poll_exit
2025-04-11 12:54:35,807 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: poll_exit
2025-04-11 12:54:35,808 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: poll_exit
2025-04-11 12:54:36,809 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: poll_exit
2025-04-11 12:54:36,810 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: poll_exit
2025-04-11 12:54:37,811 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: poll_exit
2025-04-11 12:54:37,812 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: poll_exit
2025-04-11 12:54:38,812 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: poll_exit
2025-04-11 12:54:38,813 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: poll_exit
2025-04-11 12:54:39,814 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: poll_exit
2025-04-11 12:54:39,814 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: poll_exit
2025-04-11 12:54:40,816 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: poll_exit
2025-04-11 12:54:40,817 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: poll_exit
2025-04-11 12:54:41,818 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: status_report
2025-04-11 12:54:41,819 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: poll_exit
2025-04-11 12:54:41,820 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: poll_exit
2025-04-11 12:54:42,820 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: poll_exit
2025-04-11 12:54:42,822 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: poll_exit
2025-04-11 12:54:43,331 INFO    wandb-upload_0:4234 [upload_job.py:push():131] Uploaded file /tmp/tmpvs0v_8vzwandb/xhai4ljf-wandb-metadata.json
2025-04-11 12:54:43,532 INFO    Thread-11 (_thread_body):4234 [sender.py:transition_state():613] send defer: 11
2025-04-11 12:54:43,533 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: defer
2025-04-11 12:54:43,533 INFO    HandlerThread:4234 [handler.py:handle_request_defer():172] handle defer: 11
2025-04-11 12:54:43,534 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: defer
2025-04-11 12:54:43,535 INFO    SenderThread:4234 [sender.py:send_request_defer():609] handle sender defer: 11
2025-04-11 12:54:43,535 INFO    SenderThread:4234 [file_pusher.py:join():181] waiting for file pusher
2025-04-11 12:54:43,535 INFO    SenderThread:4234 [sender.py:transition_state():613] send defer: 12
2025-04-11 12:54:43,535 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: defer
2025-04-11 12:54:43,535 INFO    HandlerThread:4234 [handler.py:handle_request_defer():172] handle defer: 12
2025-04-11 12:54:43,536 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: defer
2025-04-11 12:54:43,536 INFO    SenderThread:4234 [sender.py:send_request_defer():609] handle sender defer: 12
2025-04-11 12:54:43,536 INFO    SenderThread:4234 [file_stream.py:finish():595] file stream finish called
2025-04-11 12:54:43,807 INFO    SenderThread:4234 [file_stream.py:finish():599] file stream finish is done
2025-04-11 12:54:43,807 INFO    SenderThread:4234 [sender.py:transition_state():613] send defer: 13
2025-04-11 12:54:43,807 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: defer
2025-04-11 12:54:43,807 INFO    HandlerThread:4234 [handler.py:handle_request_defer():172] handle defer: 13
2025-04-11 12:54:43,808 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: defer
2025-04-11 12:54:43,808 INFO    SenderThread:4234 [sender.py:send_request_defer():609] handle sender defer: 13
2025-04-11 12:54:43,808 INFO    SenderThread:4234 [sender.py:transition_state():613] send defer: 14
2025-04-11 12:54:43,808 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: defer
2025-04-11 12:54:43,809 INFO    HandlerThread:4234 [handler.py:handle_request_defer():172] handle defer: 14
2025-04-11 12:54:43,809 DEBUG   SenderThread:4234 [sender.py:send():380] send: final
2025-04-11 12:54:43,810 DEBUG   SenderThread:4234 [sender.py:send():380] send: footer
2025-04-11 12:54:43,810 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: defer
2025-04-11 12:54:43,810 INFO    SenderThread:4234 [sender.py:send_request_defer():609] handle sender defer: 14
2025-04-11 12:54:43,811 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: poll_exit
2025-04-11 12:54:43,812 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: poll_exit
2025-04-11 12:54:43,813 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: poll_exit
2025-04-11 12:54:43,813 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: server_info
2025-04-11 12:54:43,813 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: get_summary
2025-04-11 12:54:43,813 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: sampled_history
2025-04-11 12:54:43,814 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: internal_messages
2025-04-11 12:54:43,814 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: poll_exit
2025-04-11 12:54:43,815 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: server_info
2025-04-11 12:54:43,818 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: job_info
2025-04-11 12:54:44,075 DEBUG   SenderThread:4234 [sender.py:send_request():407] send_request: job_info
2025-04-11 12:54:44,076 INFO    MainThread:4234 [wandb_run.py:_footer_history_summary_info():3599] rendering history
2025-04-11 12:54:44,076 INFO    MainThread:4234 [wandb_run.py:_footer_history_summary_info():3631] rendering summary
2025-04-11 12:54:44,076 INFO    MainThread:4234 [wandb_run.py:_footer_sync_info():3558] logging synced files
2025-04-11 12:54:44,077 DEBUG   HandlerThread:4234 [handler.py:handle_request():146] handle_request: shutdown
2025-04-11 12:54:44,077 INFO    HandlerThread:4234 [handler.py:finish():866] shutting down handler
2025-04-11 12:54:44,819 INFO    WriterThread:4234 [datastore.py:close():294] close: /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250411_125344-eutoc5dq/run-eutoc5dq.wandb
2025-04-11 12:54:45,075 INFO    SenderThread:4234 [sender.py:finish():1534] shutting down sender
2025-04-11 12:54:45,076 INFO    SenderThread:4234 [file_pusher.py:finish():175] shutting down file pusher
2025-04-11 12:54:45,076 INFO    SenderThread:4234 [file_pusher.py:join():181] waiting for file pusher
